add(swap):Integrated Half Button in Swap page
Ubeswap/ubeswap-interface pull request #435
Opened 2021-12-10 18:32 UTC by gsantini-ube

-Integrated Half button and Half button logic

Added button, buttong-group for buttons

![image](https://user-images.githubusercontent.com/90205715/145620609-b45b70f9-5053-455c-a2ae-eb855038658f.png)
![image](https://user-images.githubusercontent.com/90205715/145620672-79411910-971a-449c-b6e2-64182d3f35d3.png)
![image](https://user-images.githubusercontent.com/90205715/145620705-68be3f89-4112-4608-85fd-15151fc66551.png)

2021-12-10 18:39 UTC, aaronmgdr commented on src/pages/Swap/index.tsx
> +    if (maxAmountInput) {
why this maxAmount input conditional?

2021-12-10 18:40 UTC, aaronmgdr commented on src/pages/Swap/index.tsx
> +        onUserInput(Field.INPUT, (Number(maxAmountInput.toExact()) * 0.5).toString())
For half amount it doesnt matter if its CELO token or not

2021-12-10 18:40 UTC, aaronmgdr requested changes
Can we do this without adding 2 new packages ? I think so. 

Fixed. Thanks

2021-12-10 22:33 UTC, aaronmgdr commented
I think this takes up too much space on mobile but that it also would not be good for it to be smaller as buttons are already pretty small. 

I know that's not great feedback. Im not sure the best solution.

![IMG_1BDBE45EA24E-1](https://user-images.githubusercontent.com/3814795/145648800-e256bac6-ceba-4c7b-b2be-f060f921f321.jpeg)

2021-12-10 23:37 UTC, BriungRi commented
Here's a different design pattern we could adopt.
<img width="205" alt="Screen Shot 2021-12-10 at 6 36 14 PM" src="https://user-images.githubusercontent.com/8957844/145654043-f537414a-cdbd-40a0-b07d-a57a401f9648.png">

Place 4 buttons at the bottom for [25% 50% 75% 100%]

2021-12-12 17:58 UTC, gsantini-ube commented
I have changed the layout of panel.
![image](https://user-images.githubusercontent.com/95660534/145723748-06e06e4a-02ae-4de8-99b3-e24fb444e038.png)
![image](https://user-images.githubusercontent.com/95660534/145723765-550acdc5-a594-43f8-9409-d2b93ee72845.png)
![image](https://user-images.githubusercontent.com/95660534/145723789-2fdf22c0-c270-4e2e-997c-ccf53f260f0e.png)
![image](https://user-images.githubusercontent.com/95660534/145723829-0a4ed7ff-10f4-429b-9459-565a65eb9fb2.png)

2021-12-13 17:56 UTC, BriungRi commented
Can we have some additional margin right between the amount number and the 50% button?

2021-12-13 17:57 UTC, BriungRi approved these changes

2021-12-13 18:14 UTC, aaronmgdr approved these changes
I agree with Brian, needs more space between the two buttons so they can be pressed by fingers

2021-12-13 18:43 UTC, gsantini-ube commented
I changed additional margin between number input and buttons.

![image](https://user-images.githubusercontent.com/95660534/145869791-34a5a27e-881b-4cde-8e83-e7f0343484e8.png)
![image](https://user-images.githubusercontent.com/95660534/145869853-c48ebc8f-908d-43a4-9944-06fe58c1ba55.png)

2021-12-13 19:35 UTC, merged